<?php

class PtbrFaker
{
    private static $instance;
    private $faker;

    private function __construct()
    {
        $this->faker = \Faker\Factory::create('pt_BR');
    }

    public static function getInstance()
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    public static function create()
    {
        return self::getInstance()->faker;
    }

    public static function GetNeighborhood(): string
    {
        return self::getInstance()->faker->randomElement([
            'Centro',
            'Jardim América',
            'Vila Mariana',
            'Pinheiros',
            'Moema',
            'Santana',
            'Consolação',
            'Liberdade',
            'Bela Vista',
            'Aclimação',
            'Cambuci',
            'Ipiranga',
            'Vila Prudente',
            'Mooca',
            'Brás',
            'Pari',
            'Tatuapé',
            'Belém',
            'Água Rasa',
            'Anália Franco',
            'Vila Formosa',
            'Vila Carrão',
            'Aricanduva',
            'Cidade Líder',
            'Artur Alvim',
            'Itaquera',
            'José Bonifácio',
            'Cidade Tiradentes',
            'São Mateus',
            'Vila Industrial',
            'Sapopemba',
            'São Lucas',
            'Parque São Lucas',
            'Parque São Rafael',
            'Jardim Helian',
            'Vila Curuçá',
            'Jardim Nordeste',
            'Guaianases',
            'Vila Jacuí',
            'Parque São Jorge',
            'Parque do Carmo',
            'Jardim Marília',
            'Parque Cruzeiro do Sul',
            'Jardim Romano',
            'Vila União',
            'Vila Nova Manchester',
            'Jardim Brasília',
            'Vila Gomes Cardim',
            'Vila Esperança',
            'Cidade Patriarca',
            'Engenheiro Goulart',
            'Ponte Rasa',
            'Jardim Nordeste',
            'Parque Boturussu',
            'Vila Paranaguá',
            'Ermelino Matarazzo',
            'Vila Rubi',
            'Americanópolis',
            'Jabaquara',
            'Vila Guarani',
            'Vila Santa Catarina',
            'Cidade Ademar',
            'Pedreira',
            'Jardim Miriam',
            'Jardim São Savério',
            'Jardim Clímax',
            'Vila das Mercês',
            'Parque Bristol',
            'Parque Fongaro',
            'Parque Imperial',
            'Parque Independência',
            'Parque Santo Antônio',
            'Vila Arapuá',
            'Vila Liviero',
            'Vila São José',
            'Parque Cocaia',
            'Jardim Clímax',
            'Socorro',
            'Cidade Dutra',
            'Grajaú',
            'Interlagos',
            'Marsilac',
            'Varginha',
            'Parelheiros',
            'Parque Primavera',
            'Jardim Ângela',
            'Jardim São Luís',
            'Capão Redondo',
            'Jardim Líbano',
            'Jardim Umarizal',
            'Parque do Lago',
            'Parque Arariba',
            'Vila das Belezas',
            'Parque Fernanda',
            'Vila Pirajussara',
            'Parque Pinheiros',
            'Parque Munhoz',
            'Jardim Rosana',
            'Campo Limpo',
            'Vila Andrade',
            'Parque Rebouças',
            'Parque Continental',
            'Jardim Arpoador',
            'Jardim Bonfiglioli',
            'Jardim São Domingos',
            'Jardim Rolinópolis',
            'Jardim João XXIII',
            'Raposo Tavares',
            'Vila Leopoldina',
            'Vila Hamburguesa',
            'Alto de Pinheiros',
            'Jaguaré',
            'Parque Continental',
            'Jardim Boa Vista',
            'Vila Yara',
            'Jardim Ester',
            'Parque dos Príncipes',
            'Jardim Arpoador',
            'Butantã',
            'Rio Pequeno',
            'Jardim Peri',
            'Vila Nova Cachoeirinha',
            'Vila Penteado',
            'Jardim Elisa Maria',
            'Jardim Fontális',
            'Vila Zat',
            'Jaraguá',
            'Jardim Rincão',
            'Parque Nações Unidas',
            'Pirituba',
            'Vila Jaguara',
            'Vila Anastácio',
            'City América',
            'Vila Mangalot',
            'Vila Bonilha',
            'Jardim Felicidade',
            'Parque São Domingos',
            'Perus',
            'Anhanguera',
            'Jardim Britânia',
            'Jardim dos Francos',
            'Jardim Santo Elias',
            'Taipas',
            'Jardim Paulistano',
            'Jardim São Paulo',
            'Jardim São Bento',
            'Jardim França',
            'Jardim São Pedro',
            'Tremembé',
            'Parque Vitória',
            'Jardim Paraná',
            'Vila Nivi',
            'Parque Edu Chaves',
            'Jardim Japão',
            'Vila Medeiros',
            'Vila Sabrina',
            'Jardim Brasil',
            'Vila Gustavo',
            'Vila Ede',
            'Parada Inglesa',
            'Vila Isolina Mazzei',
            'Jardim São João',
            'Vila Aurora',
            'Jardim Andaraí',
            'Vila Amália',
            'Vila Albertina',
            'Jardim Fontális',
            'Vila Palmares',
            'Rudge Ramos',
            'Santa Terezinha',
            'Demarchi',
            'Jardim Atlântico',
            'Ferrazópolis',
            'Assunção',
            'Paulicéia',
            'Nova Petrópolis',
            'Jordanópolis',
            'Diadema',
            'Campanário',
            'Inamar',
            'Eldorado',
            'Piraporinha',
            'Casa Grande',
            'Vila São José',
            'Vila Santa Maria',
            'Jardim Sapopemba',
            'Vila Margarida',
            'Vila Luzita',
            'Jardim Santo André',
            'Vila João Ramalho',
            'Cidade São Jorge',
            'Utinga',
            'Parque Novo Oratório',
            'Parque Oratório',
            'Jardim Santo Antônio',
            'Jardim Ipanema',
            'Parque São Vicente',
            'Campestre',
            'Olímpico',
            'Vila Gilda',
            'Bairro Jardim',
            'Rudge Ramos',
            'Santa Paula',
            'Vila Assunção',
            'Bela Aliança'
        ]);

    }
}